kind: pipeline
name: default

steps:
- name: test
  image: python
  commands:
  - pip install -r requirements.txt
  - pytest --help

- name: docker build
  image: plugins/docker
  settings:
    tags:
      - latest
      - '1.0.1'
      - '1.0'
